image: node:12

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm run test:ci
  artifacts:
    when: always
    paths:
      # save coverage results
      - coverage
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml
      
# store and publish code coverage HTML report folder
# https://about.gitlab.com/blog/2016/11/03/publish-code-coverage-report-with-gitlab-pages/
# the coverage report will be available both as a job artifact
# and at https://gitlab.kowasoft.de/alfen-to-mqtt/
pages:
  stage: .post
  dependencies:
    - test
  script:
    # delete everything in the current public folder
    # and replace with code coverage HTML report
    - rm -rf public/*
    - cp -r coverage/lcov-report/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master